### ISSUE TITLE
Admin flag for parts that need attention

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#107]
Your "Bump":

https://library.ldraw.org/tracker/27376

gets overlooked. Since the page with parts you wanna have reviewed is gone a flag in the Parts List + as search criteria would be helpful.

**Comment by ldraw-org** [comment]
This will be taken care of with [Issue 26](https://github.com/ldraw-org/ldraworg-library/issues/26)
