### ISSUE TITLE
PT forbid to upload a patterned part having its description ending by "Pattern (Needs work)"

### ISSUE THREAD

**Issue by Cheenzo-LD** [ldraw-org/ldraworg-library#109]
PT forbid to upload a patterned part having its description ending by "Pattern (Needs work)"

**Comment by ldraw-org** [comment]
The "W" must be capitalized.

**Comment by Cheenzo-LD** [comment]
Oh thanks! I didn't know this was case sensitive. Maybe the error message could be modified from:
`Pattern part description must end with "Pattern"`
to:
`Pattern part description must end with "Pattern" or "Pattern (Needs Work)"`
