### ISSUE TITLE
What is the difference between "Search" and "Quick Search"?

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#11]
Beside the fact that "Quick Search" is broken.

**Comment by ldraw-org** [comment]
Once it's working, quick search, if it finds a single match, will take you directly to the page of the part you are searching for. That's fine if you want just that part. However, say you want all parts with "3001"? Quick search will take you to parts/3001.dat, the search page will not and there needs to be a way to get to the search page without typing jibberish into the quick search box. Also, the search page has more search options as quick search's default will be "Filename and header".
