### ISSUE TITLE
"Reset" button on voting page missing 

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#13]
In addition to the "Submit" button the voting page should have a "Reset" button as the original PT.

**Comment by ldraw-org** [comment]
Reset isn't very useful in my mind. "You current vote" has been added to the voting page to remind you of your current vote. It is also colored correctly.

**Comment by Holly-Wood68** [comment]
Ok, I got misunderstood. Maybe "Cancel" is then what I was looking for. I could either "Submit" my vote or abort the voting by hitting the "Go back to previous page" button of the browsers menu bar. I'd like to see the "Go back" button duplicated next to the "Submit" button. Just to underline that you can abort the voting without messing up anything.

**Comment by ldraw-org** [comment]
This will be fixed with issue #32
