### ISSUE TITLE
Part order in the Parts List

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#29]
One thing that has bugged me forever is the order how part with/without subs are presented.

* Currently after the "Needs admin review. (CCN)" you get parts WITHOUT subs that "Needs more votes. (CN)"
* Then you get subs, primitives, 48-segment primitives, part texture with "Needs more votes. (CN)"
* Then parts WITHOUT subs that "Needs more votes. (N)"
* Subs, primitives, primitives, 48-segment primitives, part texture with "Needs more votes. (N)"

**and only at the very end and after much scrawling**:

* Parts WITH subs where "1 subfile isn't certified. (CCSF)"

I'd like to see the parts WITHOUT/WITH subs grouped together. Actually parts WITH subs should be presented first, as they need more attention from reviewers. (You know, the more subs a part has the more it is likely that it will stay on the PT for a long, long time. Why reviewing a complicated part when your brain gets immediate gratification by casting a CERTIFY on a simple part?).

******************************

Talking about "much scrawling" it would be great to have a shortcut menu with anchors at the top that allows you to jump immediately to, say:

* Parts WITH subfiles where "* subfiles aren't certified. (CSSN)"
...
* Primitives that "Needs more votes. (CN)"
* Subpart that "Needs more votes. (N)"
...
* Parts with "1 'hold' vote. (HSN)"

**Comment by ldraw-org** [comment]
Added some filtering options. I think the categories chosen are good. Anything else is probably better off in search.
