### ISSUE TITLE
Extending the search

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#3]
https://library.ldraw.org/tracker/search

* I would welcome if could select from a drop-down menu which limits the result say to:

Needs 1 More Vote
Needs More Votes
1 Uncertified Subfile
2 Uncertified Subfile

* I wish I could search for a term and add/exclude an author from the list: Say all stickers authors by Sirio. All brick NOT authored by James

**Comment by ldraw-org** [comment]
Both of these are now implemented
