### ISSUE TITLE
Thumbnails in the activity chart

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#4]
https://library.ldraw.org/tracker/activity

I've been missing this in the old Activity for years: Thumbs

**Comment by ldraw-org** [comment]
I tried this a few months back on the live PT and the page looked too cluttered.

**Comment by Holly-Wood68** [comment]
I can cope with cluttering as I consider a visual representation of the part much more important.

**Comment by ldraw-org** [comment]
Thumbs added. Not sure I like it but we'll see what others have to say.

**Comment by Cheenzo-LD** [comment]
I also think it is really important to have more visual elements rather than text. Thumbnails are good like this and I like the new icon for comments.

**Comment by ldraw-org** [comment]
Ok. Nobody is complaining.
