### ISSUE TITLE
One thing that has bothered me from day 1

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#43]
Speeking of the Parts List with it's:

7 subfiles aren't certified. (SSSSSSSN)

or the Parts Tracker Activity with:

(CSSSSSN)

you can never tell what the status of the subfiles is without investigating the part. You come across parts with a (CCSN) and wonder why it is still there and you have to click it to find out that the sub is HOLD. What i propose is an additional information:

(CScShSSN) (CCSccScN) (ScSccShN)

Guess you already figured out what I'm looking for?

**Comment by ldraw-org** [comment]
I'm not sure about this. There's potential for these letter codes to get out of hand quickly.

**Comment by Holly-Wood68** [comment]
Maybe a table or at least line breaks for the subfiles could help to avoid a XXXXXXXXXXXXXXXXXXXXXXX worm:

C
Sch
Scc
S
Shh
N

or

C Sh Scc S
Scc N
