### ISSUE TITLE
3D preview renders images wrong

### ISSUE THREAD

**Issue by SwampKryakwa** [ldraw-org/ldraworg-library#44]
For some reason, 3D preview on the parts tracker is broken. Here's how unofficial part 19086.dat looks:
![image](https://user-images.githubusercontent.com/87991018/211778112-d0d70391-263f-4cc6-ba38-51030e3e499b.png)

Missing cyli can be seen around peg holes, that are present on the old tracker:
![image](https://user-images.githubusercontent.com/87991018/211778302-822ad466-dc12-40e9-af0c-8f0c379e8806.png)

**Comment by ldraw-org** [comment]
This bug has been traced to the library parse and import script specifically:
If the first line after the header is "0 BFC INVERTNEXT", that line is stripped from the file.

This has been fixed and this issue will be closed when the import import is performed.
