### ISSUE TITLE
Official library subfiles don't use newer unofficial subfiles for unofficial parts

### ISSUE THREAD

**Issue by SwampKryakwa** [ldraw-org/ldraworg-library#45]
When previewing parts with official library subfiles that, themselves, have subfiles with newer versions on the tracker do not use those newer versions and instead fall back to official subfiles

Part 32173 uses beamhole primitive, which uses npeghole primitive, currently with newer version on tracker, but is still drawn with older npeghole: 
![Screenshot_2023-01-11-19-12-41-559_com yandex browser](https://user-images.githubusercontent.com/87991018/211859707-e2a0a90e-912e-4b58-b4fd-cfa1f5dc3154.jpg)

On old tracker, it has proper npeghole 
![Screenshot_2023-01-11-19-14-22-290_com yandex browser](https://user-images.githubusercontent.com/87991018/211859832-fdfa3010-584c-41a9-9d30-011d6e0a142e.jpg)

**Comment by ldraw-org** [comment]
This is intentional. The official parts should render the same way as if you downloaded the complete.zip and loaded the part in LDView.

**Comment by ldraw-org** [comment]
Actually, for unofficial files, the unofficial versions should take priority. This may not be happening in referenced official subparts.

**Comment by ldraw-org** [comment]
This bug is confirmed.

**Comment by ldraw-org** [comment]
Big fixed.
