### ISSUE TITLE
Keywords are missing in File Header section of file details

### ISSUE THREAD

**Issue by Cheenzo-LD** [ldraw-org/ldraworg-library#49]
Keywords are missing in File Header section of file details

e.g. There is no keyword visible on https://library.ldraw.org/tracker/26412 while there are keywords on the same part on live PT: https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/89679pt0.dat

**Comment by ldraw-org** [comment]
It appears if all !KEYWORDS have been scrubbed. They are, however, being correctly indexed in the DB. This mean the code that formats the header is faulty.

**Comment by ldraw-org** [comment]
Big fixed. Will close when full library reimport is finished.
