### ISSUE TITLE
"Submit more parts" link from submission summery missing

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#50]
After submitting a part you get:

The following files passed validation checks and have been submitted to the Parts Tracker
24087p02.dat - [Minifigure Skirt Ruffled with Red Half Pattern](https://library.ldraw.org/tracker/29814)

The PT has a link "Submit more parts" a the bottom as a shortcut.

**Comment by ldraw-org** [comment]
Added a link and cleaned up the display table. Added a note about image creation.
