### ISSUE TITLE
Pattern/Composite/Sticker Shortcut Search

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#53]
I don't understand the Pattern/Composite/Sticker Shortcut Search page.

* First of all you have to search by a part number instead of a more useful full text such as: Shield, torso, head, set 928 ... narrowing down your search.
* A 57028p01.dat is found but 57028 returns no result.

Page looks like a placeholder for something more?

**Comment by ldraw-org** [comment]
Full text search in the pattern summary doesn't make sense. It's intended to show all the patterns of a given base part. I've added some labeling to make this more clear.

Search for 57028 fails because there is no 57028.dat which is contrary to the Library Spec.
