### ISSUE TITLE
Next File and Prev File buttons on the File detail page do not work

### ISSUE THREAD

**Issue by Cheenzo-LD** [ldraw-org/ldraworg-library#55]
Next File and Prev File buttons on the File detail page do not work (Tested with Chrome)

Also, wouldn't it be more logic to have Prev button on the left and Next on the right?

**Comment by ldraw-org** [comment]
Those are place holder items that are not yet implemented

**Comment by Holly-Wood68** [comment]
Nobody uses them.

**Comment by ldraw-org** [comment]
These have been removed.
