### ISSUE TITLE
Missing Movedto ref from a subfile

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#6]
I know that no subfile should get a Movedto to an update subfile. However if the new PT is a mirror of the old PT a sub-Movedto has been omitted. Please check:

https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/s/71645s01.dat

which is a Movedto from:

https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/s/883-1.dat

Any ref in the new PT is missing:

https://library.ldraw.org/tracker/28490

**Comment by ldraw-org** [comment]
That part is in the library but isn't being located by part lookup function.
[https://library.ldraw.org/tracker/28670](https://library.ldraw.org/tracker/28670)

**Comment by ldraw-org** [comment]
The error was with the part itself. The Name: did not contain the required "s\" which screwed up the import script. This has been fixed on the live PT and will propagate to the beta on next data import. On a side note, I thought I caught all of these errors but I'll check again.
