### ISSUE TITLE
Header Edit button missing

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#63]
The single part pages miss the "Header Edit" button next to "Download, Review/Comment" buttons.

**Comment by ldraw-org** [comment]
This is a permissions bug

**Comment by ldraw-org** [comment]
Roles with the part.edit permission cannot see the "Edit Header" menu item nor access the header edit page. This is due to the edit permissions not being present in the Part Policy file.

**Comment by ldraw-org** [comment]
Bug fixed.
