### ISSUE TITLE
Differentiate icon colors between Comment and Submit

### ISSUE THREAD

**Issue by Cheenzo-LD** [ldraw-org/ldraworg-library#65]
Curently the two icons share the same colors: black on the list and Grey on the file detail page.

It would be good to have two different colors to better distinguish them because the two black icons are very close when looking quickly:

- e.g. the comment icon could have black outline and white inside
- or the submit icon could be in yellow

It's not an important request but an easy one to implement ;)

**Comment by ldraw-org** [comment]
Comment made blue.
