### ISSUE TITLE
No quick way to download a referenced part/sub/prim

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#66]
To download a referenced part/sub/prim you have to navigate to the referenced part (or open it in an new tab) and hit the download button to get it. There is no "Download" link to the ref on the detail page itself:

https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/s/35759s04.dat

Related (unofficial) subfiles:
[Minifig Headdress Fireworks Rocket Costume](https://www.ldraw.org/cgi-bin/ptdetail.cgi?f=parts/35759.dat)
Status: 3 subfiles aren't certified. (CCSSSN)
**Download: [parts/35759.dat](https://www.ldraw.org/library/unofficial/parts/35759.dat)**
[Events](https://www.ldraw.org/cgi-bin/tracker/activity.cgi?f=parts/35759.dat)

**Comment by ldraw-org** [comment]
Added a download link to the part tables.
