### ISSUE TITLE
Add "Submit" to "Other info" column on Activity page

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#68]
The Activity page reads:

Certify with comments 
Hold with comments
Certify with no comments

but submitting just gets:

with comments
with no comments 

Should read:

"**Submit** with comments"
"**Submit** with no comments"

Otherwise you have to check the icon to understand what's going on.

**Comment by ldraw-org** [comment]
I meant to remove the certify, hold, etc. text as well. The point of the icon is to represent the action in a compact way without having to explain it in text. I realize this is a bit of a paradigm shift but it allows for more info to be on the page without it being a wall of text.

**Comment by Holly-Wood68** [comment]
Then you have to add something at least to the "CERT" for all those cases where the part is good but there is room for improvement such as T-junk, more keywords... Otherwise once a part got a green tick not followed by an esclamation mark or question mark or something like that, nobody will ever red those comments if not the admin at release.

**Comment by ldraw-org** [comment]
Maybe I wasn't clear. "with/without comments" will still be there, just the vote, which is now displayed graphically, will be removed. Or, better yet, a comment icon can be there if there were comments.

**Comment by ldraw-org** [comment]
Added a comment icon for events with comments.

**Comment by Cheenzo-LD** [comment]
Perfect like this, thanks!
