### ISSUE TITLE
Error on casting a comment

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#7]
Commented with "Test":

https://library.ldraw.org/tracker/28490/vote

Got:

BadMethodCallException
PHP 8.1.2-1ubuntu2.8
9.43.0
Method Illuminate\Http\Request::safe does not exist.

App \ Http \ Controllers \ VoteController : 74
postVote

**Comment by ldraw-org** [comment]
This is fixed

**Comment by ldraw-org** [comment]
This is fixed
