### ISSUE TITLE
Add support for helper parts

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#74]
https://forums.ldraw.org/thread-26038.html

**Comment by ldraw-org** [comment]
Already supported. That said, we should probably make the rules more formal but that's a separate issue.

**Comment by ldraw-org** [comment]
I will say that submitting a Helper part is thoroughly untested and may lead to unexpected failure.

**Comment by Holly-Wood68** [comment]
We won't find out unless we try. Let's postpone this 'til the new PT is ironed out.
