### ISSUE TITLE
Operator for Part List Sorting

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#82]
I like the sorting feature on the Parts List a lot! It would be even more useful, if it had operators linked to the sorting criteria: A radio button with "Not".

NOT Certified would therefore list all parts which aren't certified or NOT Hold
NOT Subparts but all other parts
NOT Holly-Wood but all parts by other authors

In regard of the authors an additions operator would be useful. "On PT" as the drop down lists all LDraw authors regardless if they have a part on the PT or not.

**Comment by ldraw-org** [comment]
The part author select should already be limited to only authors with parts on the PT.

**Comment by ldraw-org** [comment]
Implemented
