### ISSUE TITLE
Parts submitted via proxy miss reference

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#84]
The newly submitted parts via proxy miss the reference:

https://library.ldraw.org/tracker/29990
https://library.ldraw.org/tracker/29989

**Comment by ldraw-org** [comment]
If a fix to an official part is submitted, the submit code is not searching for and updating parts already on the tracker that use said part. 

The part listed above have been manually updated and should display correctly.

**Comment by ldraw-org** [comment]
Fixed
