### ISSUE TITLE
Weekly New Parts table misses DAT in the header

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#87]
[https://library.ldraw.org/tracker/weekly]

Table misses "DAT" in the header. Therefore "Status" is above the download links and leaves the actual status column empty.

**Comment by ldraw-org** [comment]
Weekly uses part table row component but not the part table component. Should be updated to use both.

**Comment by ldraw-org** [comment]
Fixed.
