### ISSUE TITLE
Forced rule on admin header edit 

### ISSUE THREAD

**Issue by Holly-Wood68** [ldraw-org/ldraworg-library#89]
A part submitted via proxy with the description:

0 ~Minifig Leg Right with Blue/White Triangles, Fringe Pattern (Obsolete)

cannot be edited via Admin Header Edit. Gives back the following error:

'Pattern part description must end with "Pattern"'

https://library.ldraw.org/tracker/30004

**Comment by ldraw-org** [comment]
The header edit and the submit script use similar, but not the same, validation code. This issue has been fixed with submit but since I'm working on an overhaul of header edit it has not been fixed for this function. For now, a temp work around is to resubmit the part.

**Comment by ldraw-org** [comment]
Fixed
